version: '3.8'

services:
  tg-ip-locator:
    image: ghcr.io/oliverbancroft/tg-ip-locate:latest
    container_name: tg-ip-locator
    restart: unless-stopped
    user: "1000:1000"  # Explicitly set user to match the UID:GID in Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - LOCATION=SG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s